defaults:
  - override /database@_global_: island_small
  - override /evolution@_global_: medium_budget
  - override /task@_global_: red_teaming
  - override /cluster@_global_: local
  - _self_

variant_suffix: "_example"
