import type { Metadata } from "next";
import "./globals.css";
import ContentWrapObserver from "@/components/ContentWrapObserver";
import BootEffects from "@/components/BootEffects";
import SnapToTop from "@/components/SnapToTop";
import { Exo_2 } from "next/font/google";

const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={exo2.variable}>
      <head>
        <link rel="preconnect" href="https://registry.npmmirror.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://unpkg.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://cdn.simpleicons.org" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="//registry.npmmirror.com" />
        <link rel="dns-prefetch" href="//unpkg.com" />
        <link rel="dns-prefetch" href="//cdn.simpleicons.org" />
        {/* Preload videos to reduce flicker when section enters view */}
        <link rel="preload" as="video" href="/data/videos/attempt1.mp4" type="video/mp4" />
        <link rel="preload" as="video" href="/data/videos/attempt2.mp4" type="video/mp4" />
        {/* Preload team images */}
        <link rel="preload" as="image" href="/data/images/team/arnaud.jpg" />
        <link rel="preload" as="image" href="/data/images/team/henrique.jpg" />
        {/* Preload common lab icons (webp dark) */}
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/openai.webp" />
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/google.webp" />
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/anthropic.webp" />
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/microsoft.webp" />
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/meta.webp" />
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/aws.webp" />
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/deepseek.webp" />
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/perplexity.webp" />
        <link rel="preload" as="image" href="https://registry.npmmirror.com/@lobehub/icons-static-webp/latest/files/dark/grok.webp" />
      </head>
      <body className={`antialiased font-sans`}>
        <BootEffects />
        <SnapToTop />
        <ContentWrapObserver />
        {children}
      </body>
    </html>
  );
}
